// Builds public_html/vendor/ from the pinned devDependencies, and THIRD_PARTY_NOTICES.md
// from what actually went into it. Run `npm run vendor` after changing any of them; the
// output is committed, because the site has no build step at deploy time.
//
//   vendor/markdown-kit.js   markdown-it + plugins, highlight.js, js-yaml (one IIFE)
//   vendor/mermaid/          mermaid, ESM, split so each diagram type loads on demand;
//                            built from its ESM sources rather than copied from its dist,
//                            so its dependencies get the versions (and overrides) pinned
//                            here — mermaid's prebuilt bundle carries its own lodash-es
//   vendor/purify.min.js     DOMPurify, as published
//   vendor/highlight.css     the highlight.js theme for code blocks

import { build } from "esbuild";
import { readFileSync, writeFileSync, rmSync, mkdirSync, copyFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const vendor = join(root, "public_html/vendor");
const modules = join(root, "node_modules");

rmSync(vendor, { recursive: true, force: true });
mkdirSync(vendor, { recursive: true });

const common = { bundle: true, minify: true, legalComments: "none", metafile: true, logLevel: "warning", target: "es2022" };

const kit = await build({
  ...common,
  entryPoints: [join(root, "scripts/markdown-kit.entry.js")],
  outfile: join(vendor, "markdown-kit.js"),
  format: "iife",
});

const diagrams = await build({
  ...common,
  entryPoints: { mermaid: join(modules, "mermaid/dist/mermaid.core.mjs") },
  outdir: join(vendor, "mermaid"),
  format: "esm",
  splitting: true,
  chunkNames: "chunks/[name]-[hash]",
});

const purify = readFileSync(join(modules, "dompurify/dist/purify.min.js"), "utf8").replace(/\n\/\/# sourceMappingURL=.*$/m, "");
writeFileSync(join(vendor, "purify.min.js"), purify);

copyFileSync(join(modules, "highlight.js/styles/github-dark.min.css"), join(vendor, "highlight.css"));

// ---- THIRD_PARTY_NOTICES.md -------------------------------------------------------

/** The package that owns a bundled file, found by walking up to its package.json. */
function packageOf(file) {
  let dir = dirname(join(root, file));
  while (dir.startsWith(modules) && dir !== modules) {
    const manifest = join(dir, "package.json");
    if (existsSync(manifest)) {
      const pkg = JSON.parse(readFileSync(manifest, "utf8"));
      if (pkg.name && pkg.version) return { dir, pkg };
    }
    dir = dirname(dir);
  }
  return null;
}

function licenseText(dir) {
  const file = readdirSync(dir).find((name) => /^(licen[cs]e|copying)/i.test(name));
  return file ? readFileSync(join(dir, file), "utf8").trim() : null;
}

const packages = new Map();
const note = (file, where) => {
  const found = packageOf(file);
  if (!found) return;
  const key = `${found.pkg.name}@${found.pkg.version}`;
  const entry = packages.get(key) ?? { ...found, where: new Set() };
  entry.where.add(where);
  packages.set(key, entry);
};
for (const file of Object.keys(kit.metafile.inputs)) note(file, "vendor/markdown-kit.js");
for (const file of Object.keys(diagrams.metafile.inputs)) note(file, "vendor/mermaid/");
note("node_modules/dompurify/dist/purify.min.js", "vendor/purify.min.js");
note("node_modules/highlight.js/styles/github-dark.min.css", "vendor/highlight.css");

const sections = [...packages.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, { dir, pkg, where }]) => {
    const text = licenseText(dir) ?? `Licensed under ${pkg.license}; the package ships no license file.`;
    // Four backticks: a license text may contain three.
    return `## ${key}\n\nLicense: ${pkg.license ?? "see below"}. Used in: ${[...where].join(", ")}.\n\n\`\`\`\`text\n${text}\n\`\`\`\``;
  });

writeFileSync(
  join(root, "THIRD_PARTY_NOTICES.md"),
  `# Third-party notices\n\n` +
    `Generated by \`npm run vendor\` from the packages bundled into \`public_html/vendor/\`.\n` +
    `Do not edit by hand.\n\n` +
    `DOMPurify is dual-licensed (Apache-2.0 OR MPL-2.0) and is used here under Apache-2.0.\n\n` +
    sections.join("\n\n") +
    "\n"
);

const size = (file) => `${Math.round(readFileSync(file).length / 1024)} KB`;
console.log(`markdown-kit.js ${size(join(vendor, "markdown-kit.js"))}`);
console.log(`mermaid/ entry ${size(join(vendor, "mermaid/mermaid.js"))}, ${readdirSync(join(vendor, "mermaid/chunks")).length} chunks`);
console.log(`${packages.size} packages in THIRD_PARTY_NOTICES.md`);
